### ISSUE TITLE
Database discussion and data requirements

### ISSUE THREAD

**Issue by frankhale** [DIOS-Tech/BlueHarvest#29]
This issue will track database related discussions

**Comment by frankhale** [comment]
Here are some tasks from closed related issues:

- [ ] add change log in sql https://github.com/DIOS-Tech/BlueHarvest/issues/23
- [ ] add accesslog for sql https://github.com/DIOS-Tech/BlueHarvest/issues/22
- [ ] Build phone type enum for data project https://github.com/DIOS-Tech/BlueHarvest/issues/21

**Comment by frankhale** [comment]
I think we should entertain experimentation with other types of database management systems such as a NoSQL approach using MongoDB or something similar.

**Comment by swapneeld** [comment]
:ThumbsUp for suggestion to use NoSql approach

**Comment by ybotspawn** [comment]
I could get behind that.  I'll spawn a separate issue to modify the SQL scripts to document a nosql architecture

**Comment by frankhale** [comment]
We already have a DB discussion issue open, LOL! =)

**Comment by frankhale** [comment]
As far as NoSQL options, any are on the table. If you feel like playing with one go for it. Come back and tell us what you find out. I'm gonna play around with Mongo eventually since I am familiar with it.

**Comment by ybotspawn** [comment]
Cool, I'll check out Couch and MUMPS

**Comment by frankhale** [comment]
Does the new database script cover everything in the old? If so let's remove the old.

**Comment by ybotspawn** [comment]
Yeah the old scripts can be killed

**Comment by frankhale** [comment]
Okay here is a concern, something we need to be aware of. Whether you use the C# or F# template for ASP.NET MVC it comes with an implementation of ASP.NET identity which is used for accounting for your users, eg. authentication and shit. ASP.NET identity has it's own notion of storing users that have registered inside big huge complex MICROSOFT style tables that are not human readable for the most part. That said, our best bet is to maintain a human readable user table that has a foreign key to the bullshit that MS provides in order to keep things working nicely.

**Comment by frankhale** [comment]
I'll do the leg work bridging the good with evil.

**Comment by frankhale** [comment]
Another idea is that we can just scrub all of the bullshit ASP.NET Identity stuff, roll our own. It's not all that difficult to do really. That is just more man hours, perhaps we can play nicely with what MS is providing?

**Comment by frankhale** [comment]
Request / RequestLog. I am assuming these are for vacation requests. Do we really need the log table to denote if they are changing their dates? Seems like an unnecessary complexity right now.

Instead of the RequestLog table we could add a field to the Request table to denote if the dates were changed. Then trigger a notification to the manager. Manager approves/disapproves and that field is reset.

**Comment by frankhale** [comment]
I took some time to refactor the database. I'll commit it tonight.

**Comment by ybotspawn** [comment]
Are we now using Mongo? Should I kill my work on Couch

**Comment by frankhale** [comment]
I am just taking the SQL that you created and working with it for now figuring out what data needs to be captured, how it should be laid out, etc... I'm not advocating one DBMS or the other at this point.

Let's consider this the experimentation phase. Any options are still on the table so experiment away.

**Comment by frankhale** [comment]
@ybotspawn, you have a table in the database called Addresses, this has an addressType (int) that does not have a corresponding address type lookup table. Was this an oversight? Is the Addresses table for home and work addresses?

**Comment by frankhale** [comment]
I've already fixed it, no worries.

**Comment by frankhale** [comment]
FYI, building the Visual Studio project is gonna fail most likely because the connection string in the data access layer will likely not be correct for your system

For now, until this can be made more generic fix the connection string in DataAccess.fs in the Data project.

```fsharp
type dbSchema = SqlDataConnection<"Data Source=.\SQLEXPRESS;Initial Catalog=BlueHarvest;Integrated Security=SSPI;">
let db = dbSchema.GetDataContext()
```

**Comment by frankhale** [comment]
The connection string issue has been mitigated by https://github.com/DIOS-Tech/BlueHarvest/pull/44 however it will still have to be correct in the web.config for the Data Access lib to build.

**Comment by frankhale** [comment]
Some more changes were made today. I think the database is starting to solidify. I don't think too many more changes will need to take place. The big work now is the Data Access Layer.

**Comment by frankhale** [comment]
I'm gonna close this, if there are other issues that we have not foreseen please reopen.

**Comment by frankhale** [comment]
For a NoSQL head start I've already started a JSON structure of the data which can be found here: 

https://github.com/DIOS-Tech/BlueHarvest/blob/master/Database/data.json

This could be used as a starting point for developing a MongoDB db. If that work should happen then I think a more specifically geared issue should be created to track the work.
